name: 'Continuous Compliance Action'
description: 'An action to generate check for Compliance'
branding:
  icon: lock
  color: purple
inputs:
  ruleset:
    description: 'Base64 encoded ruleset config file or url to ruleset config file.'
    required: true
  gh_token:
    description: 'Github token that has permissions to create labels, issues and has read rights to view files.'
    required: true
  target_repos:
    description: 'Target Repositories (my-org/repository,my-org/repository-2)'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/philips-labs/continuous-compliance:latest'
  args:
    - "${{ inputs.gh_token }}"
    - "${{ inputs.ruleset }}"
    - "${{ inputs.target_repos }}"