name: Check for compliancy by using the GitHub Action

on:
  workflow_dispatch:
    inputs:
      target_repos:
        description: 'Target Repositories (my-org/repository,my-org/repository-2)'     
        required: true

jobs:
  run-linter:
    name: Run Continuous Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: philips-labs/continuous-compliance-action@main
        with:
          target_repos: ${{ github.event.inputs.target_repos }}
          gh_token: ${{ secrets.TEMP_TOKEN }}
          ruleset: "https://gist.githubusercontent.com/Brend-Smits/385824d3422c0c06323bb1412cd5ba96/raw/08676dbf366a86641dd30fd5511b91afdee65adc/gistfile1.txt"